---
name: svgen
version: "{{major}}.{{minor}}.{{patch}}"
description: "A tool for working with scalable vector graphics."
entry: {{entry}}

time_command: true

requirements:
  - vcorelib>=3.6.7

dev_requirements:
  - setuptools-wrapper
  - pytest

ci_local:
  - "- run: mk python-editable"
